// Generated by Framer (6ca5d98)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addPropertyControls,
  ControlType,
  cx,
  motion,
  useSVGTemplate,
  withCSS,
} from "framer";
import * as React from "react";
import { forwardRef } from "react";
const mask = "var(--framer-icon-mask)";
const Base = /*#__PURE__*/ forwardRef(function (props, ref) {
  return /*#__PURE__*/ _jsx("svg", {
    ...props,
    ref: ref,
    children: props.children,
  });
});
const MotionSVG = motion.create(Base);
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
  const { animated, layoutId, children, ...rest } = props;
  return animated
    ? /*#__PURE__*/ _jsx(MotionSVG, {
        ...rest,
        layoutId: layoutId,
        ref: ref,
        children: children,
      })
    : /*#__PURE__*/ _jsx("svg", { ...rest, ref: ref, children: children });
});
const svg =
  '<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 0.736 L 0 17.259 C 0.005 17.527 0.153 17.772 0.388 17.902 C 0.623 18.031 0.91 18.025 1.139 17.886 L 14.647 9.625 C 14.866 9.492 15 9.254 15 8.997 C 15 8.741 14.866 8.503 14.647 8.37 L 1.139 0.109 C 0.91 -0.03 0.623 -0.036 0.388 0.093 C 0.153 0.222 0.005 0.468 0 0.736 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="17.99464343330372px" id="aA4uwAbk9" transform="translate(6.75 3.003)" width="15.000071766041629px"/><path d="M 0 0.736 L 0 17.259 C 0.005 17.527 0.153 17.772 0.388 17.902 C 0.623 18.031 0.91 18.025 1.139 17.886 L 14.647 9.625 C 14.866 9.492 15 9.254 15 8.997 C 15 8.741 14.866 8.503 14.647 8.37 L 1.139 0.109 C 0.91 -0.03 0.623 -0.036 0.388 0.093 C 0.153 0.222 0.005 0.468 0 0.736 Z" fill="transparent" height="17.99464343330372px" id="dfZTdlcyH" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(6.75 3.003)" width="15.000071766041629px"/></svg>';
const getProps = ({ alpha, color, height, id, width, width1, ...props }) => {
  return {
    ...props,
    ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
    lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
    qxTvv_EBh: alpha ?? props.qxTvv_EBh,
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const {
    style,
    className,
    layoutId,
    variant,
    ezTt3ayMo,
    lschgej4H,
    qxTvv_EBh,
    ...restProps
  } = getProps(props);
  const href = useSVGTemplate("3492944464", svg);
  return /*#__PURE__*/ _jsx(SVG, {
    ...restProps,
    className: cx("framer-Lyd6D", className),
    layoutId: layoutId,
    ref: ref,
    role: "presentation",
    style: {
      "--1m6trwb": qxTvv_EBh,
      "--21h8s6": ezTt3ayMo,
      "--pgex8v": lschgej4H,
      ...style,
    },
    viewBox: "0 0 24 24",
    children: /*#__PURE__*/ _jsx("use", { href: href }),
  });
});
const css = [
  `.framer-Lyd6D { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"ezTt3ayMo":"color","lschgej4H":"width1","qxTvv_EBh":"alpha"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Play","color":{"type":"variable","value":"21h8s6"},"set":{"localId":"vectorSet/NGVKdicsm","id":"NGVKdicsm","moduleId":"omX0gWFPqDwhaiWwf6ab"}}
 * @framerDisableUnlink true
 */ const Icon = withCSS(Component, css, "framer-Lyd6D");
Icon.displayName = "Play";
export default Icon;
addPropertyControls(Icon, {
  ezTt3ayMo: {
    defaultValue: "rgb(0, 0, 0)",
    hidden: false,
    title: "Color",
    type: ControlType.Color,
  },
  lschgej4H: {
    defaultValue: 1.5,
    displayStepper: true,
    hidden: false,
    max: 6,
    min: 0,
    step: 0.5,
    title: "Width",
    type: ControlType.Number,
  },
  qxTvv_EBh: {
    defaultValue: 0,
    displayStepper: true,
    hidden: false,
    max: 1,
    min: 0,
    step: 0.1,
    title: "Alpha",
    type: ControlType.Number,
  },
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Icon",
      slots: [],
      annotations: {
        framerVector:
          '{"name":"Play","color":{"type":"variable","value":"21h8s6"},"set":{"localId":"vectorSet/NGVKdicsm","id":"NGVKdicsm","moduleId":"omX0gWFPqDwhaiWwf6ab"}}',
        framerVariables:
          '{"ezTt3ayMo":"color","lschgej4H":"width1","qxTvv_EBh":"alpha"}',
        framerDisableUnlink: "true",
        framerImmutableVariables: "true",
        framerSupportedLayoutHeight: "any-prefer-fixed",
        framerSupportedLayoutWidth: "any-prefer-fixed",
        framerIntrinsicWidth: "24",
        framerContractVersion: "1",
        framerIntrinsicHeight: "24",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
