// Generated by Framer (ed41f9e)
import siteMetadata from "/framerusercontent.com/modules/i5WI7dSP8uLMYEAHxTM9/vixXcb4lrdrOcvNLczjL/siteMetadata.js";
export default function metadata(params, activeLocale) {
  return {
    breakpoints: [
      { hash: "1dtdk6u", mediaQuery: "(min-width: 1280px)" },
      {
        hash: "p7r21q",
        mediaQuery: "(min-width: 790px) and (max-width: 1279.98px)",
      },
      { hash: "19fy7s6", mediaQuery: "(max-width: 789.98px)" },
    ],
    description: siteMetadata(params, activeLocale).description,
    elements: { MyYxO70SW: "hero", qWF33yHYD: "ca" },
    robots: "max-image-preview:large",
    serializationId: "framer-Eh3CQ",
    title: siteMetadata(params, activeLocale).title || "Home",
    viewport: "width=device-width",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
