// Generated by Framer (ed41f9e)
export default function metadata(params, activeLocale) {
  return {
    description:
      "Meet Socks, the first dog teacher at GiggleAcademy Born on BNBChain. Educating to make a difference ツ",
    favicon:
      "/framerusercontent.com/assets/9MmTiVdHeXp0f9VArQEJS3cmGrs.png",
    robots: "max-image-preview:large",
    socialImage:
      "/framerusercontent.com/assets/CefdvpIKz8HL6CCm5gW4egSUkzw.png",
    title: "SOCKS ON BNB",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
