// Generated by Framer (ed41f9e)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  Link,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Arc from "/framerusercontent.com/modules/4S4SnR1GdEzX95H1h5mT/TDb0qbFhtN7SkrM58svb/Arc.js";
import Play from "/framerusercontent.com/modules/HAXb8usAsbryfPorbMS4/szDG4SSfU1UCFng50IhF/nyoPQewhK.js";
const PlayFonts = getFonts(Play);
const ArcFonts = getFonts(Arc);
const cycleOrder = [
  "lx3GXLgIx",
  "a2eTa0Vlq",
  "YwEy74PMH",
  "l_CM9fwIn",
  "GAtP7TuBi",
];
const serializationHash = "framer-IIyjJ";
const variantClassNames = {
  a2eTa0Vlq: "framer-v-fctqzd",
  GAtP7TuBi: "framer-v-1g4r03",
  l_CM9fwIn: "framer-v-190ye61",
  lx3GXLgIx: "framer-v-1vb0baa",
  YwEy74PMH: "framer-v-k8z6ch",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: "spring",
};
const transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Black Transparent": "GAtP7TuBi",
  "White Transparent": "l_CM9fwIn",
  Black: "YwEy74PMH",
  Blue: "lx3GXLgIx",
  White: "a2eTa0Vlq",
};
const getProps = ({
  animate,
  click,
  contraURL,
  height,
  hover,
  id,
  width,
  ...props
}) => {
  return {
    ...props,
    E3lGgktmI: contraURL ?? props.E3lGgktmI,
    kVkajOrDB: hover ?? props.kVkajOrDB,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "lx3GXLgIx",
    vVgtdqELh: click ?? props.vVgtdqELh,
    w1jKJKoHZ: animate ?? props.w1jKJKoHZ ?? true,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    E3lGgktmI,
    w1jKJKoHZ,
    kVkajOrDB,
    vVgtdqELh,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "lx3GXLgIx",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTapll7if7 = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (vVgtdqELh) {
      const res = await vVgtdqELh(...args);
      if (res === false) return false;
    }
  });
  const onMouseEnter1vwj9np = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: true });
    if (kVkajOrDB) {
      const res = await kVkajOrDB(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (baseVariant === "a2eTa0Vlq") return false;
    return true;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: E3lGgktmI,
          motionChild: true,
          nodeId: "lx3GXLgIx",
          openInNewTab: true,
          scopeId: "oKU_3IgBf",
          children: /*#__PURE__*/ _jsxs(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-1vb0baa",
              className,
              classNames
            )} framer-ufy6f0`,
            "data-framer-name": "Blue",
            "data-highlight": true,
            layoutDependency: layoutDependency,
            layoutId: "lx3GXLgIx",
            onMouseEnter: onMouseEnter1vwj9np,
            onTap: onTapll7if7,
            ref: refBinding,
            style: {
              "--border-bottom-width": "0px",
              "--border-color": "rgba(0, 0, 0, 0)",
              "--border-left-width": "0px",
              "--border-right-width": "0px",
              "--border-style": "solid",
              "--border-top-width": "0px",
              backgroundColor: "rgb(0, 153, 255)",
              borderBottomLeftRadius: "50%",
              borderBottomRightRadius: "50%",
              borderTopLeftRadius: "50%",
              borderTopRightRadius: "50%",
              boxShadow:
                "0px 0.6021873017743928px 0.6021873017743928px -1.25px rgba(0, 0, 0, 0.18), 0px 2.288533303243457px 2.288533303243457px -2.5px rgba(0, 0, 0, 0.16), 0px 10px 10px -3.75px rgba(0, 0, 0, 0.06)",
              ...style,
            },
            variants: {
              a2eTa0Vlq: {
                "--border-bottom-width": "2px",
                "--border-color": "rgb(0, 0, 0)",
                "--border-left-width": "2px",
                "--border-right-width": "2px",
                "--border-style": "solid",
                "--border-top-width": "2px",
                backgroundColor: "rgb(255, 255, 255)",
              },
              GAtP7TuBi: {
                "--border-bottom-width": "0px",
                "--border-left-width": "0px",
                "--border-right-width": "0px",
                "--border-top-width": "0px",
                backgroundColor: "rgba(0, 0, 0, 0)",
                boxShadow: "none",
              },
              l_CM9fwIn: {
                "--border-bottom-width": "0px",
                "--border-left-width": "0px",
                "--border-right-width": "0px",
                "--border-top-width": "0px",
                backgroundColor: "rgba(0, 0, 0, 0)",
                boxShadow: "none",
              },
              YwEy74PMH: {
                "--border-bottom-width": "0px",
                "--border-left-width": "0px",
                "--border-right-width": "0px",
                "--border-top-width": "0px",
                backgroundColor:
                  "var(--token-1d3eed3f-60b2-4eeb-8b1b-2d0206799803, rgb(38, 38, 38))",
              },
            },
            ...addPropertyOverrides(
              {
                a2eTa0Vlq: { "data-border": true, "data-framer-name": "White" },
                GAtP7TuBi: { "data-framer-name": "Black Transparent" },
                l_CM9fwIn: { "data-framer-name": "White Transparent" },
                YwEy74PMH: { "data-framer-name": "Black" },
              },
              baseVariant,
              gestureVariant
            ),
            children: [
              isDisplayed() &&
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-38o6hw",
                  "data-border": true,
                  "data-framer-name": "Outer",
                  layoutDependency: layoutDependency,
                  layoutId: "QqWAtyOeG",
                  style: {
                    "--border-bottom-width": "2px",
                    "--border-color": "rgb(255, 255, 255)",
                    "--border-left-width": "2px",
                    "--border-right-width": "2px",
                    "--border-style": "solid",
                    "--border-top-width": "2px",
                    borderBottomLeftRadius: "50%",
                    borderBottomRightRadius: "50%",
                    borderTopLeftRadius: "50%",
                    borderTopRightRadius: "50%",
                  },
                  variants: { GAtP7TuBi: { "--border-color": "rgb(0, 0, 0)" } },
                }),
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-hmhh2f",
                "data-border": true,
                "data-framer-name": "Inner",
                layoutDependency: layoutDependency,
                layoutId: "xfIGdL3Sn",
                style: {
                  "--border-bottom-width": "2px",
                  "--border-color": "rgb(255, 255, 255)",
                  "--border-left-width": "2px",
                  "--border-right-width": "2px",
                  "--border-style": "solid",
                  "--border-top-width": "2px",
                  borderBottomLeftRadius: "50%",
                  borderBottomRightRadius: "50%",
                  borderTopLeftRadius: "50%",
                  borderTopRightRadius: "50%",
                },
                variants: {
                  a2eTa0Vlq: {
                    "--border-color":
                      "var(--token-1d3eed3f-60b2-4eeb-8b1b-2d0206799803, rgb(38, 38, 38))",
                  },
                  GAtP7TuBi: { "--border-color": "rgb(0, 0, 0)" },
                },
                children: /*#__PURE__*/ _jsx(Play, {
                  animated: true,
                  className: "framer-110q6bx",
                  layoutDependency: layoutDependency,
                  layoutId: "oNp3mn55L",
                  style: {
                    "--1m6trwb": 0,
                    "--21h8s6": "rgb(0, 0, 0)",
                    "--pgex8v": 1.5,
                  },
                  transformTemplate: transformTemplate1,
                }),
              }),
              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                  className: "framer-5si8iv-container",
                  "data-framer-name": "Text",
                  isAuthoredByUser: true,
                  isModuleExternal: true,
                  layoutDependency: layoutDependency,
                  layoutId: "gBvjGbXnM-container",
                  name: "Text",
                  nodeId: "gBvjGbXnM",
                  rendersWithMotion: true,
                  scopeId: "oKU_3IgBf",
                  transformTemplate: transformTemplate1,
                  children: /*#__PURE__*/ _jsx(Arc, {
                    alignmentBaseline: "bottom",
                    animate: false,
                    animateDuration: 5,
                    animateEnd: 150,
                    animateStart: -50,
                    color: "rgb(255, 255, 255)",
                    cylinderHeight: 0,
                    flip: false,
                    font: {
                      font: "Inter",
                      fontSize: 12.5,
                      fontWeight: 700,
                      letterSpacing: 3.6,
                      wordSpacing: 0.8,
                    },
                    height: "100%",
                    id: "gBvjGbXnM",
                    layoutId: "gBvjGbXnM",
                    name: "Text",
                    rotate: w1jKJKoHZ,
                    rotateSpeed: 2,
                    slots: [],
                    startOffset: 0,
                    style: { height: "100%", width: "100%" },
                    text: "VERIFIED ✦ FRAMER ✦ EXPERT ✦",
                    type: "circle",
                    width: "100%",
                    ...addPropertyOverrides(
                      {
                        a2eTa0Vlq: {
                          color:
                            "var(--token-1d3eed3f-60b2-4eeb-8b1b-2d0206799803, rgb(38, 38, 38))",
                          font: {
                            font: "RUBIK",
                            fontSize: 12.5,
                            fontWeight: 600,
                            letterSpacing: 1.5,
                            wordSpacing: 0.8,
                          },
                          text: "WATCH ✦ SOCKS ✦ GIGGLE ✦ ACADEMY  ✦ ",
                        },
                        GAtP7TuBi: { color: "rgb(0, 0, 0)" },
                        YwEy74PMH: {
                          font: {
                            font: "RUBIK",
                            fontSize: 12.5,
                            fontWeight: 500,
                            letterSpacing: 4.7,
                            wordSpacing: 0.8,
                          },
                          text: "SOCKS ✦ TEACHER ✦ SOCKS ✦",
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                }),
              }),
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-1ps5scs",
                "data-framer-name": "Block",
                layoutDependency: layoutDependency,
                layoutId: "EYAufRWFQ",
                style: {
                  borderBottomLeftRadius: "50%",
                  borderBottomRightRadius: "50%",
                  borderTopLeftRadius: "50%",
                  borderTopRightRadius: "50%",
                },
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-IIyjJ.framer-ufy6f0, .framer-IIyjJ .framer-ufy6f0 { display: block; }",
  ".framer-IIyjJ.framer-1vb0baa { cursor: pointer; height: 130px; overflow: visible; position: relative; text-decoration: none; width: 130px; }",
  ".framer-IIyjJ .framer-38o6hw { flex: none; height: 94%; left: calc(50.00000000000002% - 93.84615384615384% / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 93.84615384615384% / 2); width: 94%; will-change: var(--framer-will-change-override, transform); }",
  ".framer-IIyjJ .framer-hmhh2f { flex: none; height: 57%; left: calc(50.00000000000002% - 56.92307692307692% / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 56.92307692307692% / 2); width: 57%; will-change: var(--framer-will-change-override, transform); }",
  ".framer-IIyjJ .framer-110q6bx { flex: none; height: var(--framer-aspect-ratio-supported, 32px); left: 50%; position: absolute; top: 50%; width: 32px; }",
  ".framer-IIyjJ .framer-5si8iv-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 107px); left: 50%; position: absolute; top: 50%; width: 82%; }",
  ".framer-IIyjJ .framer-1ps5scs { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-IIyjJ.framer-v-fctqzd.framer-1vb0baa, .framer-IIyjJ.framer-v-k8z6ch.framer-1vb0baa, .framer-IIyjJ.framer-v-190ye61.framer-1vb0baa, .framer-IIyjJ.framer-v-1g4r03.framer-1vb0baa { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 130px); }",
  '.framer-IIyjJ[data-border="true"]::after, .framer-IIyjJ [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 130
 * @framerIntrinsicWidth 130
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"a2eTa0Vlq":{"layout":["fixed","fixed"]},"YwEy74PMH":{"layout":["fixed","fixed"]},"l_CM9fwIn":{"layout":["fixed","fixed"]},"GAtP7TuBi":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"E3lGgktmI":"contraURL","w1jKJKoHZ":"animate","kVkajOrDB":"hover","vVgtdqELh":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FrameroKU_3IgBf = withCSS(Component, css, "framer-IIyjJ");
export default FrameroKU_3IgBf;
FrameroKU_3IgBf.displayName = "Framer Expert Badge";
FrameroKU_3IgBf.defaultProps = { height: 130, width: 130 };
addPropertyControls(FrameroKU_3IgBf, {
  variant: {
    options: ["lx3GXLgIx", "a2eTa0Vlq", "YwEy74PMH", "l_CM9fwIn", "GAtP7TuBi"],
    optionTitles: [
      "Blue",
      "White",
      "Black",
      "White Transparent",
      "Black Transparent",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
  E3lGgktmI: { title: "Contra URL", type: ControlType.Link },
  w1jKJKoHZ: {
    defaultValue: true,
    title: "Animate",
    type: ControlType.Boolean,
  },
  kVkajOrDB: { title: "Hover", type: ControlType.EventHandler },
  vVgtdqELh: { title: "Click", type: ControlType.EventHandler },
});
addFonts(
  FrameroKU_3IgBf,
  [{ explicitInter: true, fonts: [] }, ...PlayFonts, ...ArcFonts],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FrameroKU_3IgBf",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"a2eTa0Vlq":{"layout":["fixed","fixed"]},"YwEy74PMH":{"layout":["fixed","fixed"]},"l_CM9fwIn":{"layout":["fixed","fixed"]},"GAtP7TuBi":{"layout":["fixed","fixed"]}}}',
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
        framerAutoSizeImages: "true",
        framerVariables:
          '{"E3lGgktmI":"contraURL","w1jKJKoHZ":"animate","kVkajOrDB":"hover","vVgtdqELh":"click"}',
        framerIntrinsicHeight: "130",
        framerIntrinsicWidth: "130",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./oKU_3IgBf.map
