// Generated by Framer (e0edd7a)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  RichText,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useOnVariantChange,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Clipboard from "/framerusercontent.com/modules/Hj20QU19p80mpYsvesiZ/RfHh9MIwqlgi04HKZ3Qo/Clipboard.js";
import SVG from "/framerusercontent.com/modules/I1DC9cTt2FcHsDUAaRxW/pUC2Q4HS9uuwHefZZ6Oq/SVG.js";
const SVGFonts = getFonts(SVG);
const ClipboardFonts = getFonts(Clipboard);
const enabledGestures = { eXhIlGFtn: { hover: true } };
const cycleOrder = ["eXhIlGFtn", "lE2vgcM74"];
const serializationHash = "framer-OjPUZ";
const variantClassNames = {
  eXhIlGFtn: "framer-v-py1bae",
  lE2vgcM74: "framer-v-sks7h9",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = {
  damping: 45,
  delay: 0,
  mass: 1,
  stiffness: 600,
  type: "spring",
};
const transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Copied: "lE2vgcM74", Default: "eXhIlGFtn" };
const getProps = ({
  clipboardContent,
  height,
  iconCopied,
  iconCopy,
  icons,
  id,
  labelCopied,
  labels,
  width,
  ...props
}) => {
  return {
    ...props,
    aCeOAHQBL:
      labels ??
      props.aCeOAHQBL ??
      "var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5))",
    bcOKL_7fc:
      iconCopy ??
      props.bcOKL_7fc ??
      '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd" clip-rule="evenodd" d="M21 3H7V7H3V21H17V17H21V3ZM17 15H19V5H9V7H17V15Z" fill="white"/> </svg>',
    bPCJyrIbK:
      iconCopied ??
      props.bPCJyrIbK ??
      '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M3 15L9.29412 20L21 4" stroke="black" stroke-width="2" stroke-linecap="square"/> </svg>',
    PbW7K4Unr:
      icons ??
      props.PbW7K4Unr ??
      "var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5))",
    qIDNNRI0q: clipboardContent ?? props.qIDNNRI0q ?? "Copied text.",
    rIGEnoYqD: labelCopied ?? props.rIGEnoYqD ?? "Copied",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "eXhIlGFtn",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    bcOKL_7fc,
    bPCJyrIbK,
    rIGEnoYqD,
    PbW7K4Unr,
    aCeOAHQBL,
    qIDNNRI0q,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "eXhIlGFtn",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTapigsitq = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    setVariant("lE2vgcM74");
  });
  const onAppear7cjrfa = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("eXhIlGFtn"), 1500);
  });
  useOnVariantChange(baseVariant, { lE2vgcM74: onAppear7cjrfa });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (baseVariant === "lE2vgcM74") return false;
    return true;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-py1bae",
            className,
            classNames
          ),
          "data-framer-name": "Default",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "eXhIlGFtn",
          onTap: onTapigsitq,
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              "eXhIlGFtn-hover": { "data-framer-name": undefined },
              lE2vgcM74: { "data-framer-name": "Copied", onTap: undefined },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1dloa76",
              "data-framer-name": "Content - Default",
              layoutDependency: layoutDependency,
              layoutId: "LTy0B9j8q",
              style: {
                filter: "none",
                opacity: 1,
                scale: 1,
                WebkitFilter: "none",
              },
              variants: {
                "eXhIlGFtn-hover": {
                  filter: "none",
                  opacity: 1,
                  scale: 1,
                  WebkitFilter: "none",
                },
                lE2vgcM74: {
                  filter: "blur(4px)",
                  opacity: 0,
                  scale: 1.2,
                  WebkitFilter: "blur(4px)",
                },
              },
              children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                  className: "framer-1rf32ck-container",
                  isAuthoredByUser: true,
                  isModuleExternal: true,
                  layoutDependency: layoutDependency,
                  layoutId: "JDzINczNb-container",
                  nodeId: "JDzINczNb",
                  rendersWithMotion: true,
                  scopeId: "B9WaWyb4q",
                  children: /*#__PURE__*/ _jsx(SVG, {
                    customColor: PbW7K4Unr,
                    customPadding: 0,
                    customStrokeWidth: 2,
                    customSvgCode: bcOKL_7fc,
                    height: "100%",
                    id: "JDzINczNb",
                    layoutId: "JDzINczNb",
                    lineCap: "butt",
                    lineJoin: "miter",
                    style: { height: "100%", width: "100%" },
                    width: "100%",
                  }),
                }),
              }),
            }),
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-za8vf8",
              "data-framer-name": "Content - Copied",
              layoutDependency: layoutDependency,
              layoutId: "XgwYq5o5s",
              style: {
                filter: "blur(4px)",
                opacity: 0,
                scale: 0.6,
                WebkitFilter: "blur(4px)",
              },
              transformTemplate: transformTemplate1,
              variants: {
                lE2vgcM74: {
                  filter: "blur(0px)",
                  opacity: 1,
                  scale: 1,
                  WebkitFilter: "blur(0px)",
                },
              },
              children: [
                /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                  children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                    className: "framer-i4dv67-container",
                    isAuthoredByUser: true,
                    isModuleExternal: true,
                    layoutDependency: layoutDependency,
                    layoutId: "Ch1m7stGr-container",
                    nodeId: "Ch1m7stGr",
                    rendersWithMotion: true,
                    scopeId: "B9WaWyb4q",
                    children: /*#__PURE__*/ _jsx(SVG, {
                      customColor: PbW7K4Unr,
                      customPadding: 0,
                      customStrokeWidth: 2,
                      customSvgCode: bPCJyrIbK,
                      height: "100%",
                      id: "Ch1m7stGr",
                      layoutId: "Ch1m7stGr",
                      lineCap: "butt",
                      lineJoin: "miter",
                      style: { height: "100%", width: "100%" },
                      width: "100%",
                    }),
                  }),
                }),
                isDisplayed() &&
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "SW50ZXItTWVkaXVt",
                          "--framer-font-family":
                            '"Inter", "Inter Placeholder", sans-serif',
                          "--framer-font-weight": "500",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--variable-reference-aCeOAHQBL-B9WaWyb4q))",
                        },
                        children: "Copied",
                      }),
                    }),
                    className: "framer-17qgg5f",
                    fonts: ["Inter-Medium"],
                    layoutDependency: layoutDependency,
                    layoutId: "dutGdPIji",
                    style: {
                      "--extracted-r6o4lv":
                        "var(--variable-reference-aCeOAHQBL-B9WaWyb4q)",
                      "--framer-link-text-color": "rgb(0, 153, 255)",
                      "--framer-link-text-decoration": "underline",
                      "--variable-reference-aCeOAHQBL-B9WaWyb4q": aCeOAHQBL,
                    },
                    text: rIGEnoYqD,
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
              ],
            }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                  className: "framer-1rg6uff-container",
                  isAuthoredByUser: true,
                  isModuleExternal: true,
                  layoutDependency: layoutDependency,
                  layoutId: "zNPCX7cWB-container",
                  nodeId: "zNPCX7cWB",
                  rendersWithMotion: true,
                  scopeId: "B9WaWyb4q",
                  children: /*#__PURE__*/ _jsx(Clipboard, {
                    borderRadius: 100,
                    bottomLeftRadius: 100,
                    bottomRightRadius: 100,
                    color: "rgba(255, 255, 255, 0)",
                    content: qIDNNRI0q,
                    fill: "rgba(0, 102, 255, 0)",
                    font: {},
                    height: "100%",
                    id: "zNPCX7cWB",
                    isMixedBorderRadius: false,
                    label: "",
                    layoutId: "zNPCX7cWB",
                    padding: 0,
                    paddingBottom: 0,
                    paddingLeft: 0,
                    paddingPerSide: false,
                    paddingRight: 0,
                    paddingTop: 0,
                    style: { height: "100%", width: "100%" },
                    topLeftRadius: 100,
                    topRightRadius: 100,
                    width: "100%",
                  }),
                }),
              }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-OjPUZ.framer-1gonkvx, .framer-OjPUZ .framer-1gonkvx { display: block; }",
  ".framer-OjPUZ.framer-py1bae { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-OjPUZ .framer-1dloa76 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-OjPUZ .framer-1rf32ck-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 23px); position: relative; width: 23px; }",
  ".framer-OjPUZ .framer-za8vf8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; left: 49%; overflow: hidden; padding: 0px; position: absolute; top: 50%; width: min-content; z-index: 1; }",
  ".framer-OjPUZ .framer-i4dv67-container { flex: none; height: 24px; position: relative; width: 24px; }",
  ".framer-OjPUZ .framer-17qgg5f { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
  ".framer-OjPUZ .framer-1rg6uff-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; z-index: 4; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 23
 * @framerIntrinsicWidth 23
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"lE2vgcM74":{"layout":["auto","auto"]},"D2OCcdyiy":{"layout":["auto","auto"]}}}
 * @framerVariables {"bcOKL_7fc":"iconCopy","bPCJyrIbK":"iconCopied","rIGEnoYqD":"labelCopied","PbW7K4Unr":"icons","aCeOAHQBL":"labels","qIDNNRI0q":"clipboardContent"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerB9WaWyb4q = withCSS(Component, css, "framer-OjPUZ");
export default FramerB9WaWyb4q;
FramerB9WaWyb4q.displayName = "Copy Button";
FramerB9WaWyb4q.defaultProps = { height: 23, width: 23 };
addPropertyControls(FramerB9WaWyb4q, {
  variant: {
    options: ["eXhIlGFtn", "lE2vgcM74"],
    optionTitles: ["Default", "Copied"],
    title: "Variant",
    type: ControlType.Enum,
  },
  bcOKL_7fc: {
    defaultValue:
      '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd" clip-rule="evenodd" d="M21 3H7V7H3V21H17V17H21V3ZM17 15H19V5H9V7H17V15Z" fill="white"/> </svg>',
    displayTextArea: false,
    title: "Icon - Copy",
    type: ControlType.String,
  },
  bPCJyrIbK: {
    defaultValue:
      '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M3 15L9.29412 20L21 4" stroke="black" stroke-width="2" stroke-linecap="square"/> </svg>',
    displayTextArea: false,
    title: "Icon - Copied",
    type: ControlType.String,
  },
  rIGEnoYqD: {
    defaultValue: "Copied",
    displayTextArea: false,
    title: "Label - Copied",
    type: ControlType.String,
  },
  PbW7K4Unr: {
    defaultValue:
      'var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5)) /* {"name":"1"} */',
    title: "Icons",
    type: ControlType.Color,
  },
  aCeOAHQBL: {
    defaultValue:
      "var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5))",
    title: "Labels",
    type: ControlType.Color,
  },
  qIDNNRI0q: {
    defaultValue: "Copied text.",
    displayTextArea: true,
    title: "Clipboard Content",
    type: ControlType.String,
  },
});
addFonts(
  FramerB9WaWyb4q,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "/framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "/framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "/framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "/framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "/framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "/framerusercontent.com/assets/d3tHnaQIAeqiE5hGcRw4mmgWYU.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "/framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
          weight: "500",
        },
      ],
    },
    ...SVGFonts,
    ...ClipboardFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerB9WaWyb4q",
      slots: [],
      annotations: {
        framerIntrinsicHeight: "23",
        framerColorSyntax: "true",
        framerVariables:
          '{"bcOKL_7fc":"iconCopy","bPCJyrIbK":"iconCopied","rIGEnoYqD":"labelCopied","PbW7K4Unr":"icons","aCeOAHQBL":"labels","qIDNNRI0q":"clipboardContent"}',
        framerIntrinsicWidth: "23",
        framerContractVersion: "1",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"lE2vgcM74":{"layout":["auto","auto"]},"D2OCcdyiy":{"layout":["auto","auto"]}}}',
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerAutoSizeImages: "true",
        framerComponentViewportWidth: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./B9WaWyb4q.map
