// Generated by Framer (ed41f9e)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  ResolveLinks,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useRouter,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Logo from "/framerusercontent.com/modules/HlATUKqgHFuYS3vvb0iA/Yh1IXt34nD6ww76PO3xa/JdCJh0voU.js";
import Button3 from "/framerusercontent.com/modules/YctyTaCjWQ4LQ1i1Wlcf/XoYXo49ocWBlEVlz7csV/BhcthBUh2.js";
import MenuIcon from "/framerusercontent.com/modules/YkxUTzppt4dUC7QpmOCP/ArugMQFB1S6OhQmmC9u6/jbhtpYyQB.js";
import LinkWrap from "/framerusercontent.com/modules/VQjysbkwWXLA9TbbIK1j/T2KMECpHmdT1mg0qZHW7/qsZ57VqYm.js";
const LogoFonts = getFonts(Logo);
const MenuIconFonts = getFonts(MenuIcon);
const LinkWrapFonts = getFonts(LinkWrap);
const Button3Fonts = getFonts(Button3);
const cycleOrder = ["glcDLzKOr", "MZM1_WDDF", "L83upUET1"];
const serializationHash = "framer-2q2qk";
const variantClassNames = {
  glcDLzKOr: "framer-v-1roz4g3",
  L83upUET1: "framer-v-1twkuj3",
  MZM1_WDDF: "framer-v-je0taa",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = {
  damping: 40,
  delay: 0,
  mass: 1,
  stiffness: 600,
  type: "spring",
};
const transition2 = {
  delay: 0,
  duration: 0.2,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const transition3 = {
  delay: 0,
  duration: 0.4,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Phone Open": "L83upUET1",
  Desktop: "glcDLzKOr",
  Phone: "MZM1_WDDF",
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "glcDLzKOr",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "glcDLzKOr",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTap1m32y7w = activeVariantCallback(async (...args) => {
    setVariant("MZM1_WDDF");
  });
  const XKaY3MrGu1wrmm12 = activeVariantCallback(async (...args) => {
    setVariant("Uv1Q4EKDw");
  });
  const XKaY3MrGu1ij7xna = activeVariantCallback(async (...args) => {
    setVariant("L83upUET1");
  });
  const XKaY3MrGu1m32y7w = activeVariantCallback(async (...args) => {
    setVariant("MZM1_WDDF");
  });
  const brFlQ7gXH9nx8qd = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("MZM1_WDDF"), 100);
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const router = useRouter();
  const isDisplayed = () => {
    if (["MZM1_WDDF", "L83upUET1"].includes(baseVariant)) return true;
    return false;
  };
  const isDisplayed1 = () => {
    if (baseVariant === "MZM1_WDDF") return false;
    return true;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        ...addPropertyOverrides(
          {
            L83upUET1: { value: transition3 },
            MZM1_WDDF: { value: transition2 },
          },
          baseVariant,
          gestureVariant
        ),
        children: /*#__PURE__*/ _jsx(motion.nav, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1roz4g3",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          "data-hide-scrollbars": true,
          layoutDependency: layoutDependency,
          layoutId: "glcDLzKOr",
          ref: refBinding,
          style: {
            backdropFilter: "blur(0px)",
            backgroundColor: "rgb(255, 255, 255)",
            WebkitBackdropFilter: "blur(0px)",
            ...style,
          },
          ...addPropertyOverrides(
            {
              L83upUET1: { "data-framer-name": "Phone Open" },
              MZM1_WDDF: { "data-framer-name": "Phone" },
            },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-136b6fy",
            "data-framer-name": "Container",
            layoutDependency: layoutDependency,
            layoutId: "EMsStl3lx",
            children: [
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-euu91l",
                "data-framer-name": "Logo + Icon",
                layoutDependency: layoutDependency,
                layoutId: "znQ5iVwxc",
                ...addPropertyOverrides(
                  {
                    L83upUET1: { "data-highlight": true, onTap: onTap1m32y7w },
                  },
                  baseVariant,
                  gestureVariant
                ),
                children: [
                  /*#__PURE__*/ _jsx(ResolveLinks, {
                    links: [
                      {
                        href: { webPageId: "augiA20Il" },
                        implicitPathVariables: undefined,
                      },
                      {
                        href: { webPageId: "augiA20Il" },
                        implicitPathVariables: undefined,
                      },
                      {
                        href: { webPageId: "augiA20Il" },
                        implicitPathVariables: undefined,
                      },
                    ],
                    children: (resolvedLinks) =>
                      /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 36,
                        y:
                          (componentViewport?.y || 0) +
                          (0 +
                            ((componentViewport?.height || 72) - 0 - 46) / 2) +
                          5 +
                          0,
                        ...addPropertyOverrides(
                          {
                            L83upUET1: {
                              y:
                                (componentViewport?.y || 0) +
                                0 +
                                0 +
                                0 +
                                0 +
                                14,
                            },
                            MZM1_WDDF: {
                              y:
                                (componentViewport?.y || 0) +
                                0 +
                                0 +
                                0 +
                                0 +
                                14,
                            },
                          },
                          baseVariant,
                          gestureVariant
                        ),
                        children: /*#__PURE__*/ _jsx(
                          SmartComponentScopedContainer,
                          {
                            className: "framer-d1oxkw-container",
                            isModuleExternal: true,
                            layoutDependency: layoutDependency,
                            layoutId: "PlYqApU25-container",
                            nodeId: "PlYqApU25",
                            rendersWithMotion: true,
                            scopeId: "dBPSdCosD",
                            children: /*#__PURE__*/ _jsx(Logo, {
                              CXNTUyBRt: resolvedLinks[0],
                              height: "100%",
                              id: "PlYqApU25",
                              layoutId: "PlYqApU25",
                              width: "100%",
                              ...addPropertyOverrides(
                                {
                                  L83upUET1: { CXNTUyBRt: resolvedLinks[2] },
                                  MZM1_WDDF: { CXNTUyBRt: resolvedLinks[1] },
                                },
                                baseVariant,
                                gestureVariant
                              ),
                            }),
                          }
                        ),
                      }),
                  }),
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      ...addPropertyOverrides(
                        {
                          L83upUET1: {
                            height: 60,
                            width: "60px",
                            y: (componentViewport?.y || 0) + 0 + 0 + 0 + 0 + 2,
                          },
                          MZM1_WDDF: {
                            height: 60,
                            width: "60px",
                            y: (componentViewport?.y || 0) + 0 + 0 + 0 + 0 + 2,
                          },
                        },
                        baseVariant,
                        gestureVariant
                      ),
                      children: /*#__PURE__*/ _jsx(
                        SmartComponentScopedContainer,
                        {
                          className: "framer-81s2od-container",
                          "data-framer-name": "Menu Icon",
                          isModuleExternal: true,
                          layoutDependency: layoutDependency,
                          layoutId: "HIUOugpuQ-container",
                          name: "Menu Icon",
                          nodeId: "HIUOugpuQ",
                          rendersWithMotion: true,
                          scopeId: "dBPSdCosD",
                          children: /*#__PURE__*/ _jsx(MenuIcon, {
                            height: "100%",
                            id: "HIUOugpuQ",
                            layoutId: "HIUOugpuQ",
                            name: "Menu Icon",
                            variant: "yi3Hy_cZK",
                            width: "100%",
                            XKaY3MrGu: XKaY3MrGu1wrmm12,
                            ...addPropertyOverrides(
                              {
                                L83upUET1: {
                                  style: { height: "100%", width: "100%" },
                                  variant: "g2pgNrYzO",
                                  XKaY3MrGu: XKaY3MrGu1m32y7w,
                                },
                                MZM1_WDDF: {
                                  style: { height: "100%", width: "100%" },
                                  XKaY3MrGu: XKaY3MrGu1ij7xna,
                                },
                              },
                              baseVariant,
                              gestureVariant
                            ),
                          }),
                        }
                      ),
                    }),
                ],
              }),
              isDisplayed1() &&
                /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-scwl05",
                  "data-framer-name": "Links Wrap",
                  layoutDependency: layoutDependency,
                  layoutId: "IqEUaQs1x",
                  children: [
                    /*#__PURE__*/ _jsx(ResolveLinks, {
                      links: [
                        {
                          href: { webPageId: "bit_jPcy8" },
                          implicitPathVariables: undefined,
                        },
                        {
                          href: { webPageId: "bit_jPcy8" },
                          implicitPathVariables: undefined,
                        },
                      ],
                      children: (resolvedLinks1) =>
                        /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                          height: 24,
                          y:
                            (componentViewport?.y || 0) +
                            (0 +
                              ((componentViewport?.height || 72) - 0 - 46) /
                                2) +
                            11 +
                            0,
                          ...addPropertyOverrides(
                            {
                              L83upUET1: {
                                y:
                                  (componentViewport?.y || 0) +
                                  0 +
                                  0 +
                                  0 +
                                  88 +
                                  0 +
                                  0,
                              },
                            },
                            baseVariant,
                            gestureVariant
                          ),
                          children: /*#__PURE__*/ _jsx(
                            SmartComponentScopedContainer,
                            {
                              className: "framer-hj0flk-container",
                              layoutDependency: layoutDependency,
                              layoutId: "k4DQLOWPv-container",
                              nodeId: "k4DQLOWPv",
                              rendersWithMotion: true,
                              scopeId: "dBPSdCosD",
                              children: /*#__PURE__*/ _jsx(LinkWrap, {
                                height: "100%",
                                id: "k4DQLOWPv",
                                jcuP8BOF2: resolvedLinks1[0],
                                k7NjW2jq9: "Home",
                                layoutId: "k4DQLOWPv",
                                variant: "ScnR6mzJS",
                                width: "100%",
                                ...addPropertyOverrides(
                                  {
                                    L83upUET1: {
                                      brFlQ7gXH: brFlQ7gXH9nx8qd,
                                      jcuP8BOF2: resolvedLinks1[1],
                                      variant: "f9FkCxewy",
                                    },
                                  },
                                  baseVariant,
                                  gestureVariant
                                ),
                              }),
                            }
                          ),
                        }),
                    }),
                    /*#__PURE__*/ _jsx(ResolveLinks, {
                      links: [
                        {
                          href: { hash: ":qWF33yHYD", webPageId: "bit_jPcy8" },
                          implicitPathVariables: undefined,
                        },
                        {
                          href: { hash: ":qWF33yHYD", webPageId: "bit_jPcy8" },
                          implicitPathVariables: undefined,
                        },
                      ],
                      children: (resolvedLinks2) =>
                        /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                          height: 24,
                          y:
                            (componentViewport?.y || 0) +
                            (0 +
                              ((componentViewport?.height || 72) - 0 - 46) /
                                2) +
                            11 +
                            0,
                          ...addPropertyOverrides(
                            {
                              L83upUET1: {
                                y:
                                  (componentViewport?.y || 0) +
                                  0 +
                                  0 +
                                  0 +
                                  88 +
                                  0 +
                                  48,
                              },
                            },
                            baseVariant,
                            gestureVariant
                          ),
                          children: /*#__PURE__*/ _jsx(
                            SmartComponentScopedContainer,
                            {
                              className: "framer-1s0bnvz-container",
                              layoutDependency: layoutDependency,
                              layoutId: "WtxX8_758-container",
                              nodeId: "WtxX8_758",
                              rendersWithMotion: true,
                              scopeId: "dBPSdCosD",
                              children: /*#__PURE__*/ _jsx(LinkWrap, {
                                height: "100%",
                                id: "WtxX8_758",
                                jcuP8BOF2: resolvedLinks2[0],
                                k7NjW2jq9: "Contract Address",
                                layoutId: "WtxX8_758",
                                variant: "ScnR6mzJS",
                                width: "100%",
                                ...addPropertyOverrides(
                                  {
                                    L83upUET1: { jcuP8BOF2: resolvedLinks2[1] },
                                  },
                                  baseVariant,
                                  gestureVariant
                                ),
                              }),
                            }
                          ),
                        }),
                    }),
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      height: 24,
                      y:
                        (componentViewport?.y || 0) +
                        (0 + ((componentViewport?.height || 72) - 0 - 46) / 2) +
                        11 +
                        0,
                      ...addPropertyOverrides(
                        {
                          L83upUET1: {
                            y:
                              (componentViewport?.y || 0) +
                              0 +
                              0 +
                              0 +
                              88 +
                              0 +
                              96,
                          },
                        },
                        baseVariant,
                        gestureVariant
                      ),
                      children: /*#__PURE__*/ _jsx(
                        SmartComponentScopedContainer,
                        {
                          className: "framer-b1mhco-container",
                          layoutDependency: layoutDependency,
                          layoutId: "HSSTA9zI1-container",
                          nodeId: "HSSTA9zI1",
                          rendersWithMotion: true,
                          scopeId: "dBPSdCosD",
                          children: /*#__PURE__*/ _jsx(LinkWrap, {
                            height: "100%",
                            id: "HSSTA9zI1",
                            jcuP8BOF2: "https://x.com/AcademyDogSocks",
                            k7NjW2jq9: "Twitter",
                            layoutId: "HSSTA9zI1",
                            variant: "ScnR6mzJS",
                            width: "100%",
                          }),
                        }
                      ),
                    }),
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      height: 24,
                      y:
                        (componentViewport?.y || 0) +
                        (0 + ((componentViewport?.height || 72) - 0 - 46) / 2) +
                        11 +
                        0,
                      ...addPropertyOverrides(
                        {
                          L83upUET1: {
                            y:
                              (componentViewport?.y || 0) +
                              0 +
                              0 +
                              0 +
                              88 +
                              0 +
                              144,
                          },
                        },
                        baseVariant,
                        gestureVariant
                      ),
                      children: /*#__PURE__*/ _jsx(
                        SmartComponentScopedContainer,
                        {
                          className: "framer-1tmm6sq-container",
                          layoutDependency: layoutDependency,
                          layoutId: "o68uw9EfO-container",
                          nodeId: "o68uw9EfO",
                          rendersWithMotion: true,
                          scopeId: "dBPSdCosD",
                          children: /*#__PURE__*/ _jsx(LinkWrap, {
                            height: "100%",
                            id: "o68uw9EfO",
                            jcuP8BOF2:
                              "https://t.me/AcademyDogSocks",
                            k7NjW2jq9: "Community",
                            layoutId: "o68uw9EfO",
                            variant: "ScnR6mzJS",
                            width: "100%",
                          }),
                        }
                      ),
                    }),
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      height: 24,
                      y:
                        (componentViewport?.y || 0) +
                        (0 + ((componentViewport?.height || 72) - 0 - 46) / 2) +
                        11 +
                        0,
                      ...addPropertyOverrides(
                        {
                          L83upUET1: {
                            y:
                              (componentViewport?.y || 0) +
                              0 +
                              0 +
                              0 +
                              88 +
                              0 +
                              192,
                          },
                        },
                        baseVariant,
                        gestureVariant
                      ),
                      children: /*#__PURE__*/ _jsx(
                        SmartComponentScopedContainer,
                        {
                          className: "framer-lpftyx-container",
                          layoutDependency: layoutDependency,
                          layoutId: "OsIbjb5kr-container",
                          nodeId: "OsIbjb5kr",
                          rendersWithMotion: true,
                          scopeId: "dBPSdCosD",
                          children: /*#__PURE__*/ _jsx(LinkWrap, {
                            height: "100%",
                            id: "OsIbjb5kr",
                            jcuP8BOF2:
                              "https://www.dextools.io/app/en/bnb/pair-explorer/0x4ccabf53871b8095efee1143b27c0cb0afea29df",
                            k7NjW2jq9: "Dextools",
                            layoutId: "OsIbjb5kr",
                            variant: "ScnR6mzJS",
                            width: "100%",
                          }),
                        }
                      ),
                    }),
                  ],
                }),
              isDisplayed1() &&
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-4nrh0j",
                  "data-framer-name": "Button Wrap",
                  layoutDependency: layoutDependency,
                  layoutId: "RK5vMFiox",
                  children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 46,
                    y:
                      (componentViewport?.y || 0) +
                      (0 + ((componentViewport?.height || 72) - 0 - 46) / 2) +
                      0 +
                      0,
                    ...addPropertyOverrides(
                      {
                        L83upUET1: {
                          y:
                            (componentViewport?.y || 0) +
                            0 +
                            0 +
                            0 +
                            328 +
                            24 +
                            0,
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-hhh7yq-container",
                        isModuleExternal: true,
                        layoutDependency: layoutDependency,
                        layoutId: "fKX_KXsaF-container",
                        nodeId: "fKX_KXsaF",
                        rendersWithMotion: true,
                        scopeId: "dBPSdCosD",
                        children: /*#__PURE__*/ _jsx(Button3, {
                          height: "100%",
                          ICI1DQSJ0: "Purchase Socks",
                          id: "fKX_KXsaF",
                          layoutId: "fKX_KXsaF",
                          LkLxoE1IH: true,
                          MaURTmcAp: true,
                          uRnZpSnxs:
                            "https://pancakeswap.finance/swap?outputCurrency=0x4ccabf53871b8095efee1143b27c0cb0afea29df",
                          variant: "mS8fuDLXY",
                          width: "100%",
                        }),
                      }
                    ),
                  }),
                }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-2q2qk.framer-p5zyyn, .framer-2q2qk .framer-p5zyyn { display: block; }",
  ".framer-2q2qk.framer-1roz4g3 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 72px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1200px; }",
  ".framer-2q2qk .framer-136b6fy { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; max-width: 1280px; overflow: visible; padding: 0px 80px 0px 80px; position: relative; width: 1px; }",
  ".framer-2q2qk .framer-euu91l { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 250px; }",
  ".framer-2q2qk .framer-d1oxkw-container, .framer-2q2qk .framer-81s2od-container, .framer-2q2qk .framer-hj0flk-container, .framer-2q2qk .framer-1s0bnvz-container, .framer-2q2qk .framer-b1mhco-container, .framer-2q2qk .framer-1tmm6sq-container, .framer-2q2qk .framer-lpftyx-container, .framer-2q2qk .framer-hhh7yq-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-2q2qk .framer-scwl05 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-2q2qk .framer-4nrh0j { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 250px; }",
  ".framer-2q2qk.framer-v-je0taa.framer-1roz4g3 { flex-direction: column; height: 64px; justify-content: flex-start; overflow: hidden; width: 390px; }",
  ".framer-2q2qk.framer-v-je0taa .framer-136b6fy, .framer-2q2qk.framer-v-1twkuj3 .framer-136b6fy { align-content: flex-start; align-items: flex-start; flex: none; flex-direction: column; gap: 24px; padding: 0px; width: 100%; }",
  ".framer-2q2qk.framer-v-je0taa .framer-euu91l { gap: unset; height: 64px; justify-content: space-between; padding: 0px 0px 0px 16px; width: 100%; z-index: 2; }",
  ".framer-2q2qk.framer-v-je0taa .framer-81s2od-container, .framer-2q2qk.framer-v-1twkuj3 .framer-81s2od-container { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 60px); width: 60px; }",
  ".framer-2q2qk.framer-v-1twkuj3.framer-1roz4g3 { flex-direction: column; height: min-content; justify-content: flex-start; max-height: calc(var(--framer-viewport-height, 100vh) * 1); min-height: calc(var(--framer-viewport-height, 100vh) * 1); overflow: hidden; padding: 0px 0px 40px 0px; width: 390px; }",
  ".framer-2q2qk.framer-v-1twkuj3 .framer-euu91l { cursor: pointer; gap: unset; height: 64px; justify-content: space-between; padding: 0px 0px 0px 16px; width: 100%; z-index: 2; }",
  ".framer-2q2qk.framer-v-1twkuj3 .framer-scwl05 { flex: none; flex-direction: column; gap: 24px; justify-content: flex-start; padding: 0px 16px 0px 16px; width: 100%; z-index: 2; }",
  ".framer-2q2qk.framer-v-1twkuj3 .framer-4nrh0j { flex-direction: column; justify-content: center; padding: 24px 16px 0px 16px; width: 100%; z-index: 2; }",
  '.framer-2q2qk[data-hide-scrollbars="true"]::-webkit-scrollbar, .framer-2q2qk [data-hide-scrollbars="true"]::-webkit-scrollbar { width: 0px; height: 0px; }',
  '.framer-2q2qk[data-hide-scrollbars="true"]::-webkit-scrollbar-thumb, .framer-2q2qk [data-hide-scrollbars="true"]::-webkit-scrollbar-thumb { background: transparent; }',
  '.framer-2q2qk[data-hide-scrollbars="true"], .framer-2q2qk [data-hide-scrollbars="true"] { scrollbar-width: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 72
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"MZM1_WDDF":{"layout":["fixed","fixed"]},"L83upUET1":{"layout":["fixed","auto"],"constraints":[null,null,"100vh","100vh"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerdBPSdCosD = withCSS(Component, css, "framer-2q2qk");
export default FramerdBPSdCosD;
FramerdBPSdCosD.displayName = "Navigation 2";
FramerdBPSdCosD.defaultProps = { height: 72, width: 1200 };
addPropertyControls(FramerdBPSdCosD, {
  variant: {
    options: ["glcDLzKOr", "MZM1_WDDF", "L83upUET1"],
    optionTitles: ["Desktop", "Phone", "Phone Open"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  FramerdBPSdCosD,
  [
    { explicitInter: true, fonts: [] },
    ...LogoFonts,
    ...MenuIconFonts,
    ...LinkWrapFonts,
    ...Button3Fonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerdBPSdCosD",
      slots: [],
      annotations: {
        framerColorSyntax: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"MZM1_WDDF":{"layout":["fixed","fixed"]},"L83upUET1":{"layout":["fixed","auto"],"constraints":[null,null,"100vh","100vh"]}}}',
        framerIntrinsicWidth: "1200",
        framerAutoSizeImages: "true",
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerIntrinsicHeight: "72",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./dBPSdCosD.map
