// Generated by Framer (915daba)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
const cycleOrder = ["yi3Hy_cZK", "g2pgNrYzO"];
const serializationHash = "framer-cAXCN";
const variantClassNames = {
  g2pgNrYzO: "framer-v-1ed3arc",
  yi3Hy_cZK: "framer-v-imj2de",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = {
  damping: 40,
  delay: 0,
  mass: 1,
  stiffness: 600,
  type: "spring",
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Close: "g2pgNrYzO", Menu: "yi3Hy_cZK" };
const getProps = ({ height, id, tap, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "yi3Hy_cZK",
    XKaY3MrGu: tap ?? props.XKaY3MrGu,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, XKaY3MrGu, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "yi3Hy_cZK",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTapc2fruv = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (XKaY3MrGu) {
      const res = await XKaY3MrGu(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-imj2de",
            className,
            classNames
          ),
          "data-framer-name": "Menu",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "yi3Hy_cZK",
          onTap: onTapc2fruv,
          ref: ref ?? ref1,
          style: { ...style },
          ...addPropertyOverrides(
            { g2pgNrYzO: { "data-framer-name": "Close" } },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-wl03zv",
              "data-framer-name": "Bottom",
              layoutDependency: layoutDependency,
              layoutId: "EoMFttg5Y",
              style: {
                backgroundColor:
                  "var(--token-1d3eed3f-60b2-4eeb-8b1b-2d0206799803, rgb(38, 38, 38))",
                borderBottomLeftRadius: 10,
                borderBottomRightRadius: 10,
                borderTopLeftRadius: 10,
                borderTopRightRadius: 10,
                rotate: 0,
              },
              variants: { g2pgNrYzO: { rotate: -45 } },
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1lry1lh",
              "data-framer-name": "Top",
              layoutDependency: layoutDependency,
              layoutId: "Lazs9YoLD",
              style: {
                backgroundColor:
                  "var(--token-1d3eed3f-60b2-4eeb-8b1b-2d0206799803, rgb(38, 38, 38))",
                borderBottomLeftRadius: 10,
                borderBottomRightRadius: 10,
                borderTopLeftRadius: 10,
                borderTopRightRadius: 10,
                rotate: 0,
              },
              variants: { g2pgNrYzO: { rotate: 45 } },
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-cAXCN.framer-1d1ig9h, .framer-cAXCN .framer-1d1ig9h { display: block; }",
  ".framer-cAXCN.framer-imj2de { cursor: pointer; height: 60px; overflow: hidden; position: relative; width: 60px; }",
  ".framer-cAXCN .framer-wl03zv { flex: none; height: 2px; left: 16px; overflow: hidden; position: absolute; right: 16px; top: calc(58.33333333333336% - 2px / 2); will-change: var(--framer-will-change-override, transform); }",
  ".framer-cAXCN .framer-1lry1lh { flex: none; height: 2px; left: 16px; overflow: hidden; position: absolute; right: 16px; top: calc(41.66666666666669% - 2px / 2); will-change: var(--framer-will-change-override, transform); }",
  ".framer-cAXCN.framer-v-1ed3arc.framer-imj2de { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 60px); }",
  ".framer-cAXCN.framer-v-1ed3arc .framer-wl03zv, .framer-cAXCN.framer-v-1ed3arc .framer-1lry1lh { top: calc(50.00000000000002% - 2px / 2); }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 60
 * @framerIntrinsicWidth 60
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"g2pgNrYzO":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"XKaY3MrGu":"tap"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerjbhtpYyQB = withCSS(Component, css, "framer-cAXCN");
export default FramerjbhtpYyQB;
FramerjbhtpYyQB.displayName = "Menu Icon";
FramerjbhtpYyQB.defaultProps = { height: 60, width: 60 };
addPropertyControls(FramerjbhtpYyQB, {
  variant: {
    options: ["yi3Hy_cZK", "g2pgNrYzO"],
    optionTitles: ["Menu", "Close"],
    title: "Variant",
    type: ControlType.Enum,
  },
  XKaY3MrGu: { title: "Tap", type: ControlType.EventHandler },
});
addFonts(FramerjbhtpYyQB, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerjbhtpYyQB",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"g2pgNrYzO":{"layout":["fixed","fixed"]}}}',
        framerIntrinsicWidth: "60",
        framerIntrinsicHeight: "60",
        framerVariables: '{"XKaY3MrGu":"tap"}',
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./jbhtpYyQB.map
